/**
 * Scaffolding file used to store all the setups needed to run
 * tests automatically generated by EvoSuite
 * Thu Jan 21 05:12:07 GMT 2021
 */

package comp5111.assignment.cut;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class ToolBox_FaultRevealing0_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() {
    org.evosuite.runtime.RuntimeSettings.className = "comp5111.assignment.cut.ToolBox";
    org.evosuite.runtime.GuiSupport.initialize();
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100;
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000;
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true;
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED;
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT();
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime();
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {}
  }

  @AfterClass
  public static void clearEvoSuiteFramework(){
    Sandbox.resetDefaultSecurityManager();
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
  }

  @Before
  public void initTestCase(){
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler();
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode();
    setSystemProperties();
    org.evosuite.runtime.GuiSupport.setHeadless();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime();
    org.evosuite.runtime.agent.InstrumentingAgent.activate();
  }

  @After
  public void doneWithTestCase(){
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks();
    org.evosuite.runtime.classhandling.JDKClassResetter.reset();
    resetClasses();
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode();
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate();
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode();
  }

  public static void setSystemProperties() {

    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
    java.lang.System.setProperty("file.encoding", "UTF-8");
    java.lang.System.setProperty("java.awt.headless", "true");
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/f_/m0s3_2zn1rs0xp7j21hpq80r0000gn/T/");
    java.lang.System.setProperty("user.country", "GB");
    java.lang.System.setProperty("user.dir", "/Users/troublor/workspace/java/COMP5111-assignment/src/test");
    java.lang.System.setProperty("user.home", "/Users/troublor");
    java.lang.System.setProperty("user.language", "en");
    java.lang.System.setProperty("user.name", "troublor");
    java.lang.System.setProperty("user.timezone", "Asia/Hong_Kong");
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ToolBox_FaultRevealing0_ESTest_scaffolding.class.getClassLoader() ,
      "comp5111.assignment.cut.ToolBox",
      "comp5111.assignment.cut.ToolBox$StringTools",
      "comp5111.assignment.cut.ToolBox$RegExTools",
      "comp5111.assignment.cut.ToolBox$LocaleTools",
      "comp5111.assignment.cut.ToolBox$CharSequenceTools",
      "comp5111.assignment.cut.ToolBox$CharTools",
      "comp5111.assignment.cut.ToolBox$ArrayTools"
    );
  }
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException {
    mock(Class.forName("java.util.function.Supplier", false, ToolBox_FaultRevealing0_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ToolBox_FaultRevealing0_ESTest_scaffolding.class.getClassLoader());

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "comp5111.assignment.cut.ToolBox",
      "comp5111.assignment.cut.ToolBox$StringTools",
      "comp5111.assignment.cut.ToolBox$ArrayTools",
      "comp5111.assignment.cut.ToolBox$CharSequenceTools",
      "comp5111.assignment.cut.ToolBox$RegExTools",
      "comp5111.assignment.cut.ToolBox$LocaleTools",
      "comp5111.assignment.cut.ToolBox$CharTools"
    );
  }
}
